<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Muhammad Abdul Aziz</title>
    <link rel="stylesheet" href="styles.css"> <!-- You can link to your CSS file for additional styling -->
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="pdf/resume.pdf">Resume</a></li>
                <li><a href="https://www.linkedin.com/in/muhammad-azizch/">LinkedIn</a></li>
                <li><a href="https://github.com/muhammadazizch">GitHub</a></li>
            </ul>
        </nav>
    </header>

    <section class="hero">
        <img src="/images/Picture.png?raw=true" alt="Your Logo">
        <h1>Muhammad Abdul Aziz</h1>
    </section>

    <section class="content">
        <div class="about">
            <h2>About Me</h2>
            <p>Bachelor Degree in Statistics at Diponegoro University with a GPA of 3.83.</p>
            <p>I am currently a Mentee Data Scientist at Digistar Class 2023.</p>
        </div>
    </section>

    <footer>
        <p>&copy; 2023 Muhammad Abdul Aziz. All rights reserved.</p>
    </footer>
</body>
</html>
