title: <p align="center"> Muhammad Abdul Aziz </p>

logo: "/images/Picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Resume Muhammad Abdul Aziz.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/muhammad-azizch/">LinkedIn</a> |
  <a href="https://github.com/muhammadazizch">GitHub</a>
  </p>
  
  <p align="justify">
  Bachelor Degree of Statistics at Diponegoro University with GPA 3.83
  <br><br>
 Ex Mentee Data Science at Digistar Class 2023 | Independent Study at Zenius | Intern as Customer Database Supporting at PT Pegadaian
  <br><br>
  <br><br>
  <br><br>
  </p>

  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
